
try(filein "C:\Program Files\Autodesk\3ds Max 2011\Scripts\MakeToolbox\modules\MT_ParticleBake.ms") catch()

try(filein "C:\Program Files\Autodesk\3ds Max 2011\Scripts\MakeToolbox\modules\MT_TransformsBaker.ms") catch()

try(filein "C:\Program Files\Autodesk\3ds Max 2011\Scripts\MakeToolbox\modules\MT_ControllerCollapse.ms") catch()

try(filein "C:\Program Files\Autodesk\3ds Max 2011\Scripts\MakeToolbox\modules\MT_Cluster_attach.ms") catch()

try(filein "C:\Program Files\Autodesk\3ds Max 2011\Scripts\MakeToolbox\modules\MT_RivetMaker.ms") catch()

try(filein "C:\Program Files\Autodesk\3ds Max 2011\Scripts\MakeToolbox\modules\MT_ParticleConnector.ms") catch()
